#!/bin/bash
touch '\*\\'\''"Best School"\'\\*$\?\*\*\*\*\':' && echo "Best School" > '\*\\'\''"Best School"\'\\*$\?\*\*\*\*\':' && echo >> '\*\\'\''"Best School"\'\\*$\?\*\*\*\*\':' && echo "File created with the name '\*\\'\''\"Best School\"\'\\*\\$\\?\\*\\*\\*\\*\\*:'."
