#!/bin/bash
if [ -e "hello" ]; then current_owner=$(stat -c %U hello); if [ "$current_owner" == "guillaume" ]; then chown betty hello; echo "The owner of 'hello' has been changed to 'betty'."; else echo "The file 'hello' is not owned by 'guillaume'."; fi; else echo "The file 'hello' does not exist in the current directory."; fi
